version: '3.9'
services:

  cam1:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8551:8554"

  cam2:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8552:8554"

  cam3:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8553:8554"

  cam4:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8554:8554"

  cam5:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8555:8554"

  cam6:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8556:8554"

  cam7:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8557:8554"

  cam8:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8558:8554"

  cam9:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8559:8554"

  cam10:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8560:8554"

  cam11:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8561:8554"

  cam12:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8562:8554"

  cam13:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8563:8554"

  cam14:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8564:8554"

  cam15:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8565:8554"

  cam16:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8566:8554"

  cam17:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8567:8554"

  cam18:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8568:8554"

  cam19:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8569:8554"

  cam20:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8570:8554"

  cam21:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8571:8554"

  cam22:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8572:8554"

  cam23:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8573:8554"

  cam24:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8574:8554"

  cam25:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8575:8554"

  cam26:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8576:8554"

  cam27:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8577:8554"

  cam28:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8578:8554"

  cam29:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8579:8554"

  cam30:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8580:8554"

  cam31:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8581:8554"

  cam32:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8582:8554"

  cam33:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8583:8554"

  cam34:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8584:8554"

  cam35:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8585:8554"

  cam36:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8586:8554"

  cam37:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8587:8554"

  cam38:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8588:8554"

  cam39:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8589:8554"

  cam40:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8590:8554"

  cam41:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8591:8554"

  cam42:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8592:8554"

  cam43:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8593:8554"

  cam44:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8594:8554"

  cam45:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8595:8554"

  cam46:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8596:8554"

  cam47:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8597:8554"

  cam48:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8598:8554"

  cam49:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8599:8554"

  cam50:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8600:8554"

  cam51:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8601:8554"

  cam52:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8602:8554"

  cam53:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8603:8554"

  cam54:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8604:8554"

  cam55:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8605:8554"

  cam56:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8606:8554"

  cam57:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8607:8554"

  cam58:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8608:8554"

  cam59:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8609:8554"

  cam60:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8610:8554"

  cam61:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8611:8554"

  cam62:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8612:8554"

  cam63:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8613:8554"

  cam64:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8614:8554"

  cam65:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8615:8554"

  cam66:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8616:8554"

  cam67:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8617:8554"

  cam68:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8618:8554"

  cam69:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8619:8554"

  cam70:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8620:8554"

  cam71:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8621:8554"

  cam72:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8622:8554"

  cam73:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8623:8554"

  cam74:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8624:8554"

  cam75:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8625:8554"

  cam76:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8626:8554"

  cam77:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8627:8554"

  cam78:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8628:8554"

  cam79:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8629:8554"

  cam80:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8630:8554"

  cam81:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8631:8554"

  cam82:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8632:8554"

  cam83:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8633:8554"

  cam84:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8634:8554"

  cam85:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8635:8554"

  cam86:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8636:8554"

  cam87:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8637:8554"

  cam88:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8638:8554"

  cam89:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8639:8554"

  cam90:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8640:8554"

  cam91:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8641:8554"

  cam92:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8642:8554"

  cam93:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8643:8554"

  cam94:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8644:8554"

  cam95:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8645:8554"

  cam96:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8646:8554"

  cam97:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8647:8554"

  cam98:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8648:8554"

  cam99:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8649:8554"

  cam100:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8650:8554"

  cam101:
    image: rtsp_gstreamer_docker
    environment:
      RTSP_PORT: 8554
      FPS: 5
      WIDTH: 640
      HEIGHT: 480
    ports:
      - "8651:8554"

